version: '3.3'

services:
  wildfly:
    build:
      context: .
      args:
        JAR_VERSION: 0.0.1
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"

  mysql:
    image: mysql:5.7.30
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'