version: '3.8'

services:
  wildfly:
    build:
      context: ./docker/wildfly
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./target/demo-0.0.1-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/demo.war

  mysql:
    build:
      context: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'DEMO'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'